# Generated by Django 4.0.5 on 2022-06-21 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=255)),
                ('date_insert', models.DateTimeField()),
                ('regular', models.DecimalField(decimal_places=7, max_digits=7)),
                ('colonia', models.CharField(max_length=255)),
                ('numeropermiso', models.CharField(max_length=255)),
                ('fechaaplicacion', models.DateTimeField()),
                ('permisoid', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=7)),
                ('premium', models.DecimalField(decimal_places=7, max_digits=7)),
                ('razonsocial', models.CharField(max_length=255)),
                ('codigopostal', models.IntegerField()),
                ('dieasel', models.DecimalField(decimal_places=7, max_digits=7)),
            ],
        ),
    ]
