# Generated by Django 4.0.5 on 2022-06-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('calle', models.TextField(null=True)),
                ('rfc', models.TextField(null=True)),
                ('date_insert', models.DateTimeField(null=True)),
                ('regular', models.FloatField(null=True)),
                ('colonia', models.TextField(null=True)),
                ('numeropermiso', models.TextField(null=True)),
                ('fechaaplicacion', models.TextField(null=True)),
                ('permisoid', models.IntegerField(null=True)),
                ('longitude', models.TextField(null=True)),
                ('latitude', models.TextField(null=True)),
                ('premium', models.FloatField(null=True)),
                ('razonsocial', models.TextField(null=True)),
                ('codigopostal', models.TextField(null=True)),
                ('dieasel', models.FloatField(null=True)),
            ],
        ),
    ]
