# Generated by Django 4.0.5 on 2022-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_gasstation_id_gasstation__id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='longitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='premium',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='regular',
            field=models.TextField(),
        ),
    ]
