# Generated by Django 4.0.5 on 2022-06-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_gasstation_latitude_alter_gasstation_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='codigopostal',
            field=models.TextField(),
        ),
    ]
