version: "3.9"

services:
  postgres_db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nightstore
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/workdir
    ports:
      - "8181:8000"
    environment:
      - POSTGRES_NAME=nightstore
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - database

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
