version: "3.9"

services:
  postgres_db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nightstore
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  backend:
    build: ./backend
    volumes:
      - ./backend:/workdir
    ports:
      - "8181:8000"
    environment:
      - POSTGRES_NAME=nightstore
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    entrypoint: ["make", "start"]
    depends_on:
      - postgres_db
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  db_data:
    name: nightstore_db_data